cargo-features = ["edition"]

[package]
name = "shell"
version = "0.1.0"
authors = ["Swoorup Joshi <swoorupj@gmail.com>"]
edition = '2018'

[dependencies]
lazy_static = "1.1.0"
nix = "0.11.0"
matches = "0.1.8"
